services:
  - type: web
    name: ctfd
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        value: postgresql://ctfd_db_kp8t_user:ONz6QqORY3eTYTKRJGysdoFwy4T1RtAJ@dpg-d1b6n8muk2gs739dre50-a:5432/ctfd_db_kp8t
