services:
  - type: web
    name: ctfd
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ctfd-db
          property: connectionString

databases:
  - name: ctfd-db
    plan: free
